/**
 * Sample pizzerias used by the demo search provider so the whole app is usable
 * before a Google Maps key is configured.
 *
 * These are real, well-known shops, but the details here were written by hand
 * and are NOT verified — addresses, phone numbers and websites drift over time.
 * Treat this purely as demo fixture data. Set GOOGLE_MAPS_API_KEY in .env to
 * search real Google Places results instead; see README.md.
 */
export const DEMO_PLACES = [
  {
    id: 'demo-lucali',
    name: 'Lucali',
    address: '575 Henry St, Brooklyn, NY 11231',
    website: 'https://lucali.com',
    phone: '(718) 858-4086',
    lat: 40.6807,
    lng: -73.9997,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['brooklyn', 'ny', 'new york', 'coal', 'thin crust'],
  },
  {
    id: 'demo-di-fara',
    name: "Di Fara Pizza",
    address: '1424 Ave J, Brooklyn, NY 11230',
    website: 'https://difarany.com',
    phone: '(718) 258-1367',
    lat: 40.6249,
    lng: -73.9615,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['brooklyn', 'ny', 'new york', 'classic', 'slice'],
  },
  {
    id: 'demo-joes-pizza',
    name: "Joe's Pizza",
    address: '7 Carmine St, New York, NY 10014',
    website: 'https://joespizzanyc.com',
    phone: '(212) 366-1182',
    lat: 40.7305,
    lng: -74.0021,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
    tags: ['nyc', 'ny', 'new york', 'manhattan', 'slice', 'greenwich village'],
  },
  {
    id: 'demo-prince-street',
    name: 'Prince Street Pizza',
    address: '27 Prince St, New York, NY 10012',
    website: 'https://princestreetpizza.com',
    phone: '(212) 966-4100',
    lat: 40.7229,
    lng: -73.9944,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
    tags: ['nyc', 'ny', 'new york', 'manhattan', 'square', 'pepperoni', 'nolita'],
  },
  {
    id: 'demo-roberta',
    name: "Roberta's",
    address: '261 Moore St, Brooklyn, NY 11206',
    website: 'https://robertaspizza.com',
    phone: '(718) 417-1118',
    lat: 40.7050,
    lng: -73.9337,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['brooklyn', 'ny', 'new york', 'wood fired', 'bushwick'],
  },
  {
    id: 'demo-pequods',
    name: "Pequod's Pizza",
    address: '2207 N Clybourn Ave, Chicago, IL 60614',
    website: 'https://pequodspizza.com',
    phone: '(773) 327-1512',
    lat: 41.9224,
    lng: -87.6676,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['chicago', 'il', 'illinois', 'deep dish', 'pan', 'caramelized crust'],
  },
  {
    id: 'demo-lou-malnatis',
    name: "Lou Malnati's Pizzeria",
    address: '439 N Wells St, Chicago, IL 60654',
    website: 'https://www.loumalnatis.com',
    phone: '(312) 828-9800',
    lat: 41.8903,
    lng: -87.6339,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['chicago', 'il', 'illinois', 'deep dish', 'butter crust'],
  },
  {
    id: 'demo-spacca-napoli',
    name: 'Spacca Napoli Pizzeria',
    address: '1769 W Sunnyside Ave, Chicago, IL 60640',
    website: 'https://www.spaccanapolipizzeria.com',
    phone: '(773) 878-2420',
    lat: 41.9633,
    lng: -87.6795,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['chicago', 'il', 'illinois', 'neapolitan', 'wood fired'],
  },
  {
    id: 'demo-pizzeria-bianco',
    name: 'Pizzeria Bianco',
    address: '623 E Adams St, Phoenix, AZ 85004',
    website: 'https://pizzeriabianco.com',
    phone: '(602) 258-8300',
    lat: 33.4485,
    lng: -112.0631,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['phoenix', 'az', 'arizona', 'wood fired', 'neapolitan'],
  },
  {
    id: 'demo-tony-pizza-napoletana',
    name: "Tony's Pizza Napoletana",
    address: '1570 Stockton St, San Francisco, CA 94133',
    website: 'https://tonyspizzanapoletana.com',
    phone: '(415) 835-9888',
    lat: 37.8004,
    lng: -122.4090,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['san francisco', 'sf', 'ca', 'california', 'neapolitan', 'north beach'],
  },
  {
    id: 'demo-golden-boy',
    name: 'Golden Boy Pizza',
    address: '542 Green St, San Francisco, CA 94133',
    website: 'https://goldenboypizza.com',
    phone: '(415) 982-9738',
    lat: 37.7995,
    lng: -122.4082,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
    tags: ['san francisco', 'sf', 'ca', 'california', 'sicilian', 'square', 'focaccia'],
  },
  {
    id: 'demo-apizza-scholls',
    name: 'Apizza Scholls',
    address: '4741 SE Hawthorne Blvd, Portland, OR 97215',
    website: 'https://apizzascholls.com',
    phone: '(503) 233-1286',
    lat: 45.5121,
    lng: -122.6142,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['portland', 'or', 'oregon', 'new haven', 'thin crust'],
  },
  {
    id: 'demo-frank-pepe',
    name: 'Frank Pepe Pizzeria Napoletana',
    address: '157 Wooster St, New Haven, CT 06511',
    website: 'https://pepespizzeria.com',
    phone: '(203) 865-5762',
    lat: 41.3037,
    lng: -72.9187,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['new haven', 'ct', 'connecticut', 'apizza', 'coal', 'clam pie'],
  },
  {
    id: 'demo-sallys-apizza',
    name: "Sally's Apizza",
    address: '237 Wooster St, New Haven, CT 06511',
    website: 'https://sallysapizza.com',
    phone: '(203) 624-5271',
    lat: 41.3033,
    lng: -72.9174,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['new haven', 'ct', 'connecticut', 'apizza', 'coal'],
  },
  {
    id: 'demo-modern-apizza',
    name: 'Modern Apizza',
    address: '874 State St, New Haven, CT 06511',
    website: 'https://modernapizza.com',
    phone: '(203) 776-5306',
    lat: 41.3169,
    lng: -72.9199,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['new haven', 'ct', 'connecticut', 'apizza'],
  },
  {
    id: 'demo-pizzeria-beddia',
    name: 'Pizzeria Beddia',
    address: '1313 N Lee St, Philadelphia, PA 19125',
    website: 'https://pizzeriabeddia.com',
    phone: '(267) 928-2256',
    lat: 39.9705,
    lng: -75.1341,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['philadelphia', 'philly', 'pa', 'pennsylvania', 'fishtown'],
  },
  {
    id: 'demo-santarpios',
    name: "Santarpio's Pizza",
    address: '111 Chelsea St, Boston, MA 02128',
    website: 'https://santarpiospizza.com',
    phone: '(617) 567-9871',
    lat: 42.3742,
    lng: -71.0388,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
    tags: ['boston', 'ma', 'massachusetts', 'east boston', 'classic'],
  },
  {
    id: 'demo-regina-pizzeria',
    name: 'Regina Pizzeria',
    address: '11 1/2 Thacher St, Boston, MA 02113',
    website: 'https://www.reginapizzeria.com',
    phone: '(617) 227-0765',
    lat: 42.3652,
    lng: -71.0570,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['boston', 'ma', 'massachusetts', 'north end', 'brick oven'],
  },
  {
    id: 'demo-home-slice',
    name: 'Home Slice Pizza',
    address: '1415 S Congress Ave, Austin, TX 78704',
    website: 'https://homeslicepizza.com',
    phone: '(512) 444-7437',
    lat: 30.2497,
    lng: -97.7501,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['austin', 'tx', 'texas', 'new york style', 'south congress'],
  },
  {
    id: 'demo-via-313',
    name: 'Via 313 Pizza',
    address: '1111 E 6th St, Austin, TX 78702',
    website: 'https://via313.com',
    phone: '(512) 802-5343',
    lat: 30.2648,
    lng: -97.7307,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['austin', 'tx', 'texas', 'detroit style', 'square', 'pan'],
  },
  {
    id: 'demo-buddys',
    name: "Buddy's Pizza",
    address: '17125 Conant St, Detroit, MI 48212',
    website: 'https://www.buddyspizza.com',
    phone: '(313) 892-9001',
    lat: 42.4180,
    lng: -83.0574,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['detroit', 'mi', 'michigan', 'detroit style', 'square', 'pan'],
  },
  {
    id: 'demo-pizzeria-mozza',
    name: 'Pizzeria Mozza',
    address: '641 N Highland Ave, Los Angeles, CA 90036',
    website: 'https://www.pizzeriamozza.com',
    phone: '(323) 297-0101',
    lat: 34.0827,
    lng: -118.3387,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_EXPENSIVE',
    tags: ['los angeles', 'la', 'ca', 'california', 'hollywood'],
  },
  {
    id: 'demo-apollonia',
    name: "Apollonia's Pizzeria",
    address: '5176 Wilshire Blvd, Los Angeles, CA 90036',
    website: 'https://www.apolloniaspizzeria.com',
    phone: '(323) 937-2503',
    lat: 34.0625,
    lng: -118.3452,
    rating: 4.6,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['los angeles', 'la', 'ca', 'california', 'new york style'],
  },
  {
    id: 'demo-serious-pie',
    name: 'Serious Pie',
    address: '316 Virginia St, Seattle, WA 98101',
    website: 'https://www.seriouspieseattle.com',
    phone: '(206) 838-7388',
    lat: 47.6142,
    lng: -122.3421,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['seattle', 'wa', 'washington', 'blistered crust'],
  },
  {
    id: 'demo-antico',
    name: 'Antico Pizza Napoletana',
    address: '1093 Hemphill Ave NW, Atlanta, GA 30318',
    website: 'https://www.anticopizza.com',
    phone: '(404) 724-2333',
    lat: 33.7823,
    lng: -84.4123,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['atlanta', 'ga', 'georgia', 'neapolitan', 'wood fired'],
  },
  {
    id: 'demo-vitos',
    name: "Vito's Pizza",
    address: '846 N La Cienega Blvd, Los Angeles, CA 90069',
    website: 'https://www.vitopizza.com',
    phone: '(310) 652-6859',
    lat: 34.0836,
    lng: -118.3765,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['los angeles', 'la', 'ca', 'california', 'new york style'],
  },
  {
    id: 'demo-emmy-squared',
    name: 'Emmy Squared Pizza',
    address: '364 Grand St, Brooklyn, NY 11211',
    website: 'https://emmysquaredpizza.com',
    phone: '(718) 360-4535',
    lat: 40.7124,
    lng: -73.9524,
    rating: 4.4,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['brooklyn', 'ny', 'new york', 'detroit style', 'square'],
  },
  {
    id: 'demo-paulie-gee',
    name: "Paulie Gee's",
    address: '60 Greenpoint Ave, Brooklyn, NY 11222',
    website: 'https://pauliegee.com',
    phone: '(347) 987-3747',
    lat: 40.7297,
    lng: -73.9583,
    rating: 4.5,
    priceLevel: 'PRICE_LEVEL_MODERATE',
    tags: ['brooklyn', 'ny', 'new york', 'greenpoint', 'wood fired'],
  },
];
